### ISSUE TITLE
Add support for groups

### ISSUE THREAD

**Issue by egegunes** [geerlingguy/ansible-role-supervisor#29]
I use [groups](http://supervisord.org/configuration.html#group-x-section-settings) to start and stop related processes. I think I should be able to configure groups using this role. It can be configured like this:

```
- supervisor_groups:
    - name: 'django'
      programs:
        - 'gunicorn'
        - 'celery'
```
If you're interested, I can submit a PR.
