### ISSUE TITLE
Changing supervisor_started or supervisor_enabled to `false` doesn't stop/disable the service

### ISSUE THREAD

**Issue by brnl** [geerlingguy/ansible-role-supervisor#52]
Changing `supervisor_started` or `supervisor_enabled` to false doesn't respectively stop and disable the service, as I would expect. Once you have ran the playbook with them set to `true` there is no way back.

The role only checks for `true` statements:

```yml
- name: Ensure Supervisor is started (if configured).
  service:
    name: supervisord
    state: started
  when: supervisor_started

- name: Ensure Supervisor is enabled at boot (if configured).
  service:
    name: supervisord
    enabled: true
  when: supervisor_enabled
```

I'd assume there would also a `false` scenario:

```yml
- name: Ensure Supervisor is stopped (if configured).
  service:
    name: supervisord
    state: stopped
  when: not supervisor_started

- name: Ensure Supervisor is disabled at boot (if configured).
  service:
    name: supervisord
    enabled: false
  when: not supervisor_enabled
```

What do you think?
