### ISSUE TITLE
Unable to find any of pip3 to use.  pip needs to be installed.

### ISSUE THREAD

**Issue by numediaweb** [geerlingguy/ansible-role-supervisor#55]
I cannot run this role on Ubuntu 20.4 :
```
TASK [supervisor : Ensure Supervisor is installed.] ****************************
fatal: [snfreports-com]: FAILED! => {"changed": false, "msg": "Unable to find any of pip3 to use.  pip needs to be installed."}
```

I fixed it with:
```


- name: install pip3
  apt:
    name:
      - python3-pip
    state: present

- name: Ensure pip requirements exist on host are installed.
  pip:
    name:
      - setuptools
      - virtualenv
    state: present

- name: Ensure Supervisor is installed.
  pip:
    name: supervisor
    state: present
    version: "{{ supervisor_version | default(omit) }}"
```
