### ISSUE TITLE
var supervisor_programs list vs dict

### ISSUE THREAD

**Issue by ahivert** [geerlingguy/ansible-role-supervisor#8]
Is there a reason to use a list in place of a dict to define `supervisor_programs` ?

You define it like this:
```yaml
supervisor_programs:
    - name: 'apache'
        command: "{{ apache_start_command }}"
        state: present
        configuration: |
            autostart=true
            autorestart=true
            startretries=1
            startsecs=1
            redirect_stderr=true
            stderr_logfile=/var/log/apache-err.log
            stdout_logfile=/var/log/apache-out.log
            user=root
            killasgroup=true
            stopasgroup=true
```

Why not define it like this:
```yaml
supervisor_programs:
    apache:
        command: "{{ apache_start_command }}"
        state: present
        autostart: true
        autorestart: true
        startretries: 1
        startsecs: 1
        redirect_stderr: true
        stderr_logfile: /var/log/apache-err.log
        stdout_logfile: /var/log/apache-out.log
        user: root
        killasgroup: true
        stopasgroup: true
```

It will simplify a little the programm conf template:
```j2
[program:{{ item.key }}]
{% for option, value in item.value.iteritems() %}
{{ option }} = {{ value }}
{% endfor %}
```

Maybe I miss something :confused:
